trigger:
  batch: true
  tags:
    include:
    - 1.*
  branches:
    include:
    - main
    - releases/*
  
pool:
  name: default
  demands:
  - Agent.OS -equals Windows_NT
  
parameters:
- name: projects
  type: object
  default:
  - Matrix.Sdk

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: NuGetToolInstaller@1
  displayName:  "NuGet Install"
  inputs:
    versionSpec: 6.1.0
    checkLatest: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Build\Packages'
    Contents: '*'
    RemoveSourceFolder: true

- task: CmdLine@2
  inputs:
    script: |
      echo "Structure of work folder of this pipeline:"
      tree $(Agent.WorkFolder)\1 /f
      
      echo "Build.ArtifactStagingDirectory:" 
      
      echo "$(Build.ArtifactStagingDirectory)"
      
      echo "Build.BinariesDirectory:" 
      
      echo "$(Build.BinariesDirectory)"
      
      echo "Build.SourcesDirectory:"
    
- ${{ each project in parameters.projects }}:
  - script: echo ${{ project }}
  - task: DotNetCoreCLI@2
    displayName: 'Restore ${{ project }}'
    inputs:
      command: 'restore'
      feedsToUse: config
      nugetConfigPath: NuGet.DevOps.config

      projects: '${{ project }}/${{ project }}.csproj'
      restoreArguments: '/p:Configuration=$(BuildConfiguration) '

  - task: DotNetCoreCLI@2
    displayName: 'Build ${{ project }}'
    inputs:
      command: 'build'
      projects: '${{ project }}/${{ project }}.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Pack ${{ project }}'
    inputs:
      command: custom
      projects: ${{ project }}/${{ project }}.csproj
      custom: pack
      arguments: '--output $(Build.SourcesDirectory)\Build\Packages --no-build /p:PackageVersion=$(GitVersion.FullSemVer) /p:Configuration=$(BuildConfiguration) '

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Build\Packages'
    ArtifactName: 'packages'
    publishLocation: 'Container'
